---
- name: "configure server and basic install"
  hosts: all
  roles:
    - user
    - timezone
    - setup
    - cron
- name: "install frontend"
  hosts: watens-frontend
  roles:
    - frontend
- name: "install backend"
  hosts: watens-backend
  roles:
    - backend
