---
- name: "Create user group(s)"
  group:
    name: "{{ user }}"
    state: present
- name: "Add the user {{ user }}"
  user:
    name: "{{ user }}"
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_bits: 2048
    groups: "{{ user }}"
    ssh_key_file: .ssh/id_rsa
    append: yes
- name: Set authorized key taken from file
  authorized_key:
     user: "{{ user }}"
     state: present
     key: "{{ lookup('file', 'file/authorized_keys') }}"

- name: "Enable including files from sudoers.d/"
  lineinfile:
    path: "/etc/sudoers"
    regexp: "^#includedir /etc/sudoers.d"
    line: "#includedir /etc/sudoers.d"
    state: "present"
    backup: True
  when: user_enable_passwordless_sudo
- name: "Enable passwordless sudo"
  copy:
    content: "%{{ user }} ALL=(ALL) NOPASSWD:ALL"
    dest: "/etc/sudoers.d/{{ user }}"
    owner: "root"
    group: "root"
    mode: "0440"
  when: user_enable_passwordless_sudo