---
- name: update apt cache if needed.
  become: yes
  become_method: sudo
  apt: update_cache=yes cache_valid_time=3600
- name: install apt tools
  apt: name={{item}} state=present
  with_items:
       - python-apt
       - python-pycurl
       - python-mysqldb
