---
- name: start redis,nginx,php
  service: "name={{ item }} state=started enabled=yes"
  with_items:
       - nginx
       - php7.2-fpm
       - redis-server
- name: start redis,nginx,php
  service: "name={{ item }} state=restarted enabled=yes"
  with_items:
       - nginx
       - php7.2-fpm
       - redis-server